id: AD74C4D4D
title: Prayer for the Long Life of Lochen Ngawang Chöpal
type: translation
pechas:
- I4E148101
- IE82A2D24
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:51:55.102879
  last_modified_at: 2023-01-04 11:51:55.103028
  collections:
  - Fifth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  I4E148101/818B: 0C73
  IE82A2D24/81CA: 0C73
